namespace TaskManager;

partial class Form1
{
    private System.ComponentModel.IContainer components = null!;
    private TabControl mainTabControl = null!;
    private TabPage processesTabPage = null!;
    private TabPage startupTabPage = null!;
    private TabPage servicesTabPage = null!;
    private TabPage callsTabPage = null!;
    private SplitContainer processesSplitContainer = null!;
    private TreeView processTreeView = null!;
    private DataGridView processGrid = null!;
    private Panel processToolbarPanel = null!;
    private Button refreshProcessesButton = null!;
    private Button endTaskButton = null!;
    private Label processSearchLabel = null!;
    private TextBox processSearchTextBox = null!;
    private Label processStatusLabel = null!;
    private GroupBox processDetailsGroup = null!;
    private TableLayoutPanel detailsTableLayoutPanel = null!;
    private Label detailsNameValueLabel = null!;
    private Label detailsPidValueLabel = null!;
    private Label detailsParentValueLabel = null!;
    private Label detailsStatusValueLabel = null!;
    private Label detailsMemoryValueLabel = null!;
    private Label detailsPathValueLabel = null!;
    private Label securityDetailsLabel = null!;
    private RichTextBox securityDetailsTextBox = null!;
    private DataGridView startupGrid = null!;
    private Panel startupToolbarPanel = null!;
    private Button refreshStartupButton = null!;
    private Label startupStatusLabel = null!;
    private DataGridView servicesGrid = null!;
    private Panel servicesToolbarPanel = null!;
    private Button refreshServicesButton = null!;
    private Button startServiceButton = null!;
    private Button stopServiceButton = null!;
    private Label servicesStatusLabel = null!;
    private DataGridView callsGrid = null!;
    private Panel callsToolbarPanel = null!;
    private Button clearCallsButton = null!;
    private Label callsStatusLabel = null!;
    private ContextMenuStrip processContextMenu = null!;
    private ToolStripMenuItem endTaskToolStripMenuItem = null!;
    private ToolStripMenuItem openFileLocationToolStripMenuItem = null!;
    private MenuStrip mainMenuStrip = null!;
    private ToolStripMenuItem fileToolStripMenuItem = null!;
    private ToolStripMenuItem refreshProcessesToolStripMenuItem = null!;
    private ToolStripMenuItem refreshStartupToolStripMenuItem = null!;
    private ToolStripMenuItem refreshServicesToolStripMenuItem = null!;
    private ToolStripSeparator fileMenuSeparator1 = null!;
    private ToolStripMenuItem endTaskMenuToolStripMenuItem = null!;
    private Panel tabHeaderPanel = null!;
    private Button processesTabButton = null!;
    private Button startupTabButton = null!;
    private Button servicesTabButton = null!;
    private Button callsTabButton = null!;

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        mainTabControl = new TabControl();
        processesTabPage = new TabPage();
        startupTabPage = new TabPage();
        servicesTabPage = new TabPage();
        callsTabPage = new TabPage();
        processesSplitContainer = new SplitContainer();
        processTreeView = new TreeView();
        processGrid = new DataGridView();
        processToolbarPanel = new Panel();
        refreshProcessesButton = new Button();
        endTaskButton = new Button();
        processSearchLabel = new Label();
        processSearchTextBox = new TextBox();
        processStatusLabel = new Label();
        processDetailsGroup = new GroupBox();
        detailsTableLayoutPanel = new TableLayoutPanel();
        securityDetailsLabel = new Label();
        securityDetailsTextBox = new RichTextBox();
        startupGrid = new DataGridView();
        startupToolbarPanel = new Panel();
        refreshStartupButton = new Button();
        startupStatusLabel = new Label();
        servicesGrid = new DataGridView();
        servicesToolbarPanel = new Panel();
        refreshServicesButton = new Button();
        startServiceButton = new Button();
        stopServiceButton = new Button();
        servicesStatusLabel = new Label();
        callsGrid = new DataGridView();
        callsToolbarPanel = new Panel();
        clearCallsButton = new Button();
        callsStatusLabel = new Label();
        processContextMenu = new ContextMenuStrip(components);
        endTaskToolStripMenuItem = new ToolStripMenuItem();
        openFileLocationToolStripMenuItem = new ToolStripMenuItem();
        mainMenuStrip = new MenuStrip();
        fileToolStripMenuItem = new ToolStripMenuItem();
        refreshProcessesToolStripMenuItem = new ToolStripMenuItem();
        refreshStartupToolStripMenuItem = new ToolStripMenuItem();
        refreshServicesToolStripMenuItem = new ToolStripMenuItem();
        fileMenuSeparator1 = new ToolStripSeparator();
        endTaskMenuToolStripMenuItem = new ToolStripMenuItem();
        tabHeaderPanel = new Panel();
        processesTabButton = new Button();
        startupTabButton = new Button();
        servicesTabButton = new Button();
        callsTabButton = new Button();
        mainTabControl.SuspendLayout();
        processesTabPage.SuspendLayout();
        startupTabPage.SuspendLayout();
        servicesTabPage.SuspendLayout();
        callsTabPage.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)processesSplitContainer).BeginInit();
        processesSplitContainer.Panel1.SuspendLayout();
        processesSplitContainer.Panel2.SuspendLayout();
        processesSplitContainer.SuspendLayout();
        processToolbarPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)processGrid).BeginInit();
        processDetailsGroup.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)startupGrid).BeginInit();
        startupToolbarPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)servicesGrid).BeginInit();
        servicesToolbarPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)callsGrid).BeginInit();
        callsToolbarPanel.SuspendLayout();
        processContextMenu.SuspendLayout();
        mainMenuStrip.SuspendLayout();
        tabHeaderPanel.SuspendLayout();
        SuspendLayout();
        mainMenuStrip.Items.AddRange([fileToolStripMenuItem]);
        mainMenuStrip.BackColor = Color.FromArgb(15, 22, 30);
        mainMenuStrip.Dock = DockStyle.Top;
        mainMenuStrip.ForeColor = Color.FromArgb(226, 232, 240);
        mainMenuStrip.Font = new Font("Segoe UI", 9F);
        mainMenuStrip.Padding = new Padding(8, 2, 0, 2);
        fileToolStripMenuItem.DropDownItems.AddRange([refreshProcessesToolStripMenuItem, refreshStartupToolStripMenuItem, refreshServicesToolStripMenuItem, fileMenuSeparator1, endTaskMenuToolStripMenuItem]);
        fileToolStripMenuItem.Text = "File";
        refreshProcessesToolStripMenuItem.Text = "Refresh Processes";
        refreshProcessesToolStripMenuItem.Click += refreshProcessesButton_Click;
        refreshStartupToolStripMenuItem.Text = "Refresh Startup";
        refreshStartupToolStripMenuItem.Click += refreshStartupButton_Click;
        refreshServicesToolStripMenuItem.Text = "Refresh Services";
        refreshServicesToolStripMenuItem.Click += refreshServicesButton_Click;
        endTaskMenuToolStripMenuItem.Text = "End Task";
        endTaskMenuToolStripMenuItem.Click += endTaskButton_Click;
        tabHeaderPanel.Controls.Add(callsTabButton);
        tabHeaderPanel.Controls.Add(servicesTabButton);
        tabHeaderPanel.Controls.Add(startupTabButton);
        tabHeaderPanel.Controls.Add(processesTabButton);
        tabHeaderPanel.BackColor = Color.FromArgb(15, 22, 30);
        tabHeaderPanel.Dock = DockStyle.Top;
        tabHeaderPanel.Height = 40;
        processesTabButton.BackColor = Color.FromArgb(30, 41, 59);
        processesTabButton.FlatAppearance.BorderColor = Color.FromArgb(51, 65, 85);
        processesTabButton.FlatStyle = FlatStyle.Flat;
        processesTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        processesTabButton.ForeColor = Color.FromArgb(241, 245, 249);
        processesTabButton.Location = new Point(0, 5);
        processesTabButton.Size = new Size(84, 30);
        processesTabButton.Text = "Processes";
        processesTabButton.UseVisualStyleBackColor = false;
        processesTabButton.Click += processesTabButton_Click;
        startupTabButton.BackColor = Color.FromArgb(15, 22, 30);
        startupTabButton.FlatAppearance.BorderColor = Color.FromArgb(51, 65, 85);
        startupTabButton.FlatStyle = FlatStyle.Flat;
        startupTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        startupTabButton.ForeColor = Color.FromArgb(148, 163, 184);
        startupTabButton.Location = new Point(86, 5);
        startupTabButton.Size = new Size(66, 30);
        startupTabButton.Text = "Startup";
        startupTabButton.UseVisualStyleBackColor = false;
        startupTabButton.Click += startupTabButton_Click;
        servicesTabButton.BackColor = Color.FromArgb(15, 22, 30);
        servicesTabButton.FlatAppearance.BorderColor = Color.FromArgb(51, 65, 85);
        servicesTabButton.FlatStyle = FlatStyle.Flat;
        servicesTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        servicesTabButton.ForeColor = Color.FromArgb(148, 163, 184);
        servicesTabButton.Location = new Point(154, 5);
        servicesTabButton.Size = new Size(70, 30);
        servicesTabButton.Text = "Services";
        servicesTabButton.UseVisualStyleBackColor = false;
        servicesTabButton.Click += servicesTabButton_Click;
        callsTabButton.BackColor = Color.FromArgb(15, 22, 30);
        callsTabButton.FlatAppearance.BorderColor = Color.FromArgb(51, 65, 85);
        callsTabButton.FlatStyle = FlatStyle.Flat;
        callsTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        callsTabButton.ForeColor = Color.FromArgb(148, 163, 184);
        callsTabButton.Location = new Point(226, 5);
        callsTabButton.Size = new Size(62, 30);
        callsTabButton.Text = "Calls";
        callsTabButton.UseVisualStyleBackColor = false;
        callsTabButton.Click += callsTabButton_Click;
        mainTabControl.Controls.Add(processesTabPage);
        mainTabControl.Controls.Add(startupTabPage);
        mainTabControl.Controls.Add(servicesTabPage);
        mainTabControl.Controls.Add(callsTabPage);
        mainTabControl.Dock = DockStyle.Fill;
        mainTabControl.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        mainTabControl.ItemSize = new Size(0, 1);
        mainTabControl.Padding = new Point(0, 0);
        mainTabControl.SelectedIndex = 0;
        mainTabControl.Size = new Size(1280, 760);
        mainTabControl.SizeMode = TabSizeMode.Fixed;
        mainTabControl.BackColor = Color.FromArgb(15, 22, 30);
        mainTabControl.SelectedIndexChanged += mainTabControl_SelectedIndexChanged;
        processesTabPage.BackColor = Color.FromArgb(20, 27, 35);
        processesTabPage.Controls.Add(processesSplitContainer);
        processesTabPage.Controls.Add(processToolbarPanel);
        processesTabPage.Padding = new Padding(8);
        processesTabPage.Text = "Processes";
        startupTabPage.BackColor = Color.FromArgb(20, 27, 35);
        startupTabPage.Controls.Add(startupGrid);
        startupTabPage.Controls.Add(startupToolbarPanel);
        startupTabPage.Padding = new Padding(8);
        startupTabPage.Text = "Startup";
        servicesTabPage.BackColor = Color.FromArgb(20, 27, 35);
        servicesTabPage.Controls.Add(servicesGrid);
        servicesTabPage.Controls.Add(servicesToolbarPanel);
        servicesTabPage.Padding = new Padding(8);
        servicesTabPage.Text = "Services";
        callsTabPage.BackColor = Color.FromArgb(20, 27, 35);
        callsTabPage.Controls.Add(callsGrid);
        callsTabPage.Controls.Add(callsToolbarPanel);
        callsTabPage.Padding = new Padding(8);
        callsTabPage.Text = "Calls";
        processesSplitContainer.Dock = DockStyle.Fill;
        processesSplitContainer.FixedPanel = FixedPanel.Panel2;
        processesSplitContainer.Location = new Point(8, 62);
        processesSplitContainer.SplitterWidth = 8;
        processesSplitContainer.Panel1.Controls.Add(processGrid);
        processesSplitContainer.Panel2.Controls.Add(processDetailsGroup);
        processesSplitContainer.BackColor = Color.FromArgb(44, 54, 65);
        processGrid.AllowUserToAddRows = false;
        processGrid.AllowUserToDeleteRows = false;
        processGrid.AllowUserToOrderColumns = true;
        processGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        processGrid.BackgroundColor = Color.FromArgb(18, 24, 32);
        processGrid.BorderStyle = BorderStyle.FixedSingle;
        processGrid.ColumnHeadersHeight = 48;
        processGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        processGrid.Dock = DockStyle.Fill;
        processGrid.EnableHeadersVisualStyles = false;
        processGrid.GridColor = Color.FromArgb(38, 47, 58);
        processGrid.MultiSelect = false;
        processGrid.ReadOnly = true;
        processGrid.RowHeadersVisible = false;
        processGrid.RowTemplate.Height = 28;
        processGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        processGrid.BackgroundColor = Color.FromArgb(18, 24, 32);
        processGrid.DefaultCellStyle.BackColor = Color.FromArgb(18, 24, 32);
        processGrid.DefaultCellStyle.ForeColor = Color.FromArgb(226, 232, 240);
        processGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(36, 45, 56);
        processGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(241, 245, 249);
        processGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(20, 27, 35);
        processGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(241, 245, 249);
        processGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        processGrid.Font = new Font("Segoe UI", 9F);
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "NameColumn", HeaderText = "Name", Width = 280, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "ProcessNameColumn", HeaderText = "Process name", Width = 140, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "PidColumn", HeaderText = "PID", Width = 70, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "CpuColumn", HeaderText = "CPU", Width = 70, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "MemoryColumn", HeaderText = "Memory", Width = 90, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "GpuColumn", HeaderText = "GPU", Width = 70, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "DiskColumn", HeaderText = "Disk", Width = 70, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "NetworkColumn", HeaderText = "Network", Width = 80, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "StatusColumn", HeaderText = "Status", Width = 100, SortMode = DataGridViewColumnSortMode.NotSortable });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "CommandLineColumn", HeaderText = "Command line", Width = 360, MinimumWidth = 360, AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill, FillWeight = 100F, SortMode = DataGridViewColumnSortMode.NotSortable });
        processToolbarPanel.Controls.Add(processSearchTextBox);
        processToolbarPanel.Controls.Add(processSearchLabel);
        processToolbarPanel.Controls.Add(processStatusLabel);
        processToolbarPanel.BackColor = Color.FromArgb(15, 22, 30);
        processToolbarPanel.Dock = DockStyle.Top;
        processToolbarPanel.Height = 54;
        refreshProcessesButton.BackColor = Color.FromArgb(37, 99, 235);
        refreshProcessesButton.FlatStyle = FlatStyle.Flat;
        refreshProcessesButton.ForeColor = Color.White;
        refreshProcessesButton.Font = new Font("Consolas", 9F, FontStyle.Bold);
        refreshProcessesButton.Location = new Point(0, 12);
        refreshProcessesButton.Size = new Size(90, 30);
        refreshProcessesButton.FlatAppearance.BorderSize = 0;
        refreshProcessesButton.Text = "Refresh";
        refreshProcessesButton.UseVisualStyleBackColor = false;
        refreshProcessesButton.Visible = false;
        refreshProcessesButton.Click += refreshProcessesButton_Click;
        endTaskButton.BackColor = Color.FromArgb(185, 65, 65);
        endTaskButton.Enabled = false;
        endTaskButton.FlatStyle = FlatStyle.Flat;
        endTaskButton.ForeColor = Color.White;
        endTaskButton.Font = new Font("Consolas", 9F, FontStyle.Bold);
        endTaskButton.Location = new Point(100, 12);
        endTaskButton.Size = new Size(90, 30);
        endTaskButton.FlatAppearance.BorderSize = 0;
        endTaskButton.Text = "End Task";
        endTaskButton.UseVisualStyleBackColor = false;
        endTaskButton.Visible = false;
        endTaskButton.Click += endTaskButton_Click;
        processSearchLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        processSearchLabel.ForeColor = Color.FromArgb(148, 163, 184);
        processSearchLabel.Location = new Point(0, 16);
        processSearchLabel.Size = new Size(48, 20);
        processSearchLabel.Text = "Search";
        processSearchTextBox.BackColor = Color.FromArgb(12, 18, 24);
        processSearchTextBox.BorderStyle = BorderStyle.FixedSingle;
        processSearchTextBox.Font = new Font("Consolas", 9.5F);
        processSearchTextBox.ForeColor = Color.FromArgb(226, 232, 240);
        processSearchTextBox.Location = new Point(56, 13);
        processSearchTextBox.Size = new Size(220, 22);
        processSearchTextBox.TextChanged += processSearchTextBox_TextChanged;
        processStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        processStatusLabel.Font = new Font("Segoe UI", 9.5F);
        processStatusLabel.ForeColor = Color.FromArgb(148, 163, 184);
        processStatusLabel.Location = new Point(292, 14);
        processStatusLabel.Size = new Size(890, 24);
        processStatusLabel.Text = "Reading processes...";
        processStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        processDetailsGroup.Controls.Add(detailsTableLayoutPanel);
        processDetailsGroup.Dock = DockStyle.Fill;
        processDetailsGroup.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        processDetailsGroup.ForeColor = Color.FromArgb(203, 213, 225);
        processDetailsGroup.BackColor = Color.FromArgb(20, 27, 35);
        processDetailsGroup.Padding = new Padding(10);
        processDetailsGroup.Text = "Selected Process";
        detailsTableLayoutPanel.ColumnCount = 1;
        detailsTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        detailsTableLayoutPanel.Dock = DockStyle.Fill;
        detailsTableLayoutPanel.BackColor = Color.FromArgb(20, 27, 35);
        detailsTableLayoutPanel.RowCount = 8;
        detailsTableLayoutPanel.Padding = new Padding(0, 6, 0, 0);
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 64F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        AddDetailRow(0, "Name", out detailsNameValueLabel);
        AddDetailRow(1, "PID", out detailsPidValueLabel);
        AddDetailRow(2, "Parent PID", out detailsParentValueLabel);
        AddDetailRow(3, "Status", out detailsStatusValueLabel);
        AddDetailRow(4, "Memory", out detailsMemoryValueLabel);
        AddDetailRow(5, "Path", out detailsPathValueLabel);
        securityDetailsLabel.Dock = DockStyle.Fill;
        securityDetailsLabel.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        securityDetailsLabel.ForeColor = Color.FromArgb(148, 163, 184);
        securityDetailsLabel.Text = "Security";
        securityDetailsLabel.TextAlign = ContentAlignment.MiddleLeft;
        detailsTableLayoutPanel.Controls.Add(securityDetailsLabel, 0, 6);
        securityDetailsTextBox.BackColor = Color.FromArgb(12, 18, 24);
        securityDetailsTextBox.BorderStyle = BorderStyle.FixedSingle;
        securityDetailsTextBox.Dock = DockStyle.Fill;
        securityDetailsTextBox.Font = new Font("Consolas", 9F);
        securityDetailsTextBox.ForeColor = Color.FromArgb(226, 232, 240);
        securityDetailsTextBox.Margin = new Padding(0);
        securityDetailsTextBox.ReadOnly = true;
        securityDetailsTextBox.ScrollBars = RichTextBoxScrollBars.Vertical;
        securityDetailsTextBox.Text = "Select a process to inspect binary details.";
        detailsTableLayoutPanel.Controls.Add(securityDetailsTextBox, 0, 7);
        startupGrid.AllowUserToAddRows = false;
        startupGrid.AllowUserToDeleteRows = false;
        startupGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        startupGrid.BackgroundColor = Color.FromArgb(15, 22, 30);
        startupGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        startupGrid.Columns.Add("StartupName", "Name");
        startupGrid.Columns.Add("StartupScope", "Scope");
        startupGrid.Columns.Add("StartupType", "Type");
        startupGrid.Columns.Add("StartupLocation", "Location");
        startupGrid.Columns.Add("StartupCommand", "Command");
        startupGrid.Dock = DockStyle.Fill;
        startupGrid.EnableHeadersVisualStyles = false;
        startupGrid.DefaultCellStyle.BackColor = Color.FromArgb(18, 24, 32);
        startupGrid.DefaultCellStyle.ForeColor = Color.FromArgb(226, 232, 240);
        startupGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(30, 64, 100);
        startupGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(241, 245, 249);
        startupGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(28, 37, 49);
        startupGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(203, 213, 225);
        startupGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        startupGrid.Font = new Font("Segoe UI", 9.25F);
        startupGrid.GridColor = Color.FromArgb(51, 65, 85);
        startupGrid.MultiSelect = false;
        startupGrid.ReadOnly = true;
        startupGrid.RowHeadersVisible = false;
        startupGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        startupToolbarPanel.Controls.Add(refreshStartupButton);
        startupToolbarPanel.Controls.Add(startupStatusLabel);
        startupToolbarPanel.BackColor = Color.FromArgb(15, 22, 30);
        startupToolbarPanel.Dock = DockStyle.Top;
        startupToolbarPanel.Height = 54;
        refreshStartupButton.BackColor = Color.FromArgb(37, 99, 235);
        refreshStartupButton.FlatStyle = FlatStyle.Flat;
        refreshStartupButton.ForeColor = Color.White;
        refreshStartupButton.Font = new Font("Consolas", 9F, FontStyle.Bold);
        refreshStartupButton.Location = new Point(0, 12);
        refreshStartupButton.Size = new Size(90, 30);
        refreshStartupButton.FlatAppearance.BorderSize = 0;
        refreshStartupButton.Text = "Refresh";
        refreshStartupButton.UseVisualStyleBackColor = false;
        refreshStartupButton.Click += refreshStartupButton_Click;
        startupStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        startupStatusLabel.Font = new Font("Segoe UI", 9.5F);
        startupStatusLabel.ForeColor = Color.FromArgb(148, 163, 184);
        startupStatusLabel.Location = new Point(110, 14);
        startupStatusLabel.Size = new Size(1100, 24);
        startupStatusLabel.Text = "Reading startup items...";
        startupStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        servicesGrid.AllowUserToAddRows = false;
        servicesGrid.AllowUserToDeleteRows = false;
        servicesGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        servicesGrid.BackgroundColor = Color.FromArgb(15, 22, 30);
        servicesGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        servicesGrid.Columns.Add("ServiceDisplayName", "Display Name");
        servicesGrid.Columns.Add("ServiceName", "Service Name");
        servicesGrid.Columns.Add("ServiceStatus", "Status");
        servicesGrid.Columns.Add("ServiceStartType", "Start Type");
        servicesGrid.Dock = DockStyle.Fill;
        servicesGrid.EnableHeadersVisualStyles = false;
        servicesGrid.DefaultCellStyle.BackColor = Color.FromArgb(18, 24, 32);
        servicesGrid.DefaultCellStyle.ForeColor = Color.FromArgb(226, 232, 240);
        servicesGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(30, 64, 100);
        servicesGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(241, 245, 249);
        servicesGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(28, 37, 49);
        servicesGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(203, 213, 225);
        servicesGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        servicesGrid.Font = new Font("Segoe UI", 9.25F);
        servicesGrid.GridColor = Color.FromArgb(51, 65, 85);
        servicesGrid.MultiSelect = false;
        servicesGrid.ReadOnly = true;
        servicesGrid.RowHeadersVisible = false;
        servicesGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        servicesGrid.SelectionChanged += servicesGrid_SelectionChanged;
        servicesToolbarPanel.Controls.Add(refreshServicesButton);
        servicesToolbarPanel.Controls.Add(startServiceButton);
        servicesToolbarPanel.Controls.Add(stopServiceButton);
        servicesToolbarPanel.Controls.Add(servicesStatusLabel);
        servicesToolbarPanel.BackColor = Color.FromArgb(15, 22, 30);
        servicesToolbarPanel.Dock = DockStyle.Top;
        servicesToolbarPanel.Height = 54;
        refreshServicesButton.BackColor = Color.FromArgb(37, 99, 235);
        refreshServicesButton.FlatStyle = FlatStyle.Flat;
        refreshServicesButton.ForeColor = Color.White;
        refreshServicesButton.Font = new Font("Consolas", 9F, FontStyle.Bold);
        refreshServicesButton.Location = new Point(0, 12);
        refreshServicesButton.Size = new Size(90, 30);
        refreshServicesButton.FlatAppearance.BorderSize = 0;
        refreshServicesButton.Text = "Refresh";
        refreshServicesButton.UseVisualStyleBackColor = false;
        refreshServicesButton.Click += refreshServicesButton_Click;
        startServiceButton.BackColor = Color.FromArgb(42, 109, 81);
        startServiceButton.Enabled = false;
        startServiceButton.FlatStyle = FlatStyle.Flat;
        startServiceButton.ForeColor = Color.White;
        startServiceButton.Font = new Font("Consolas", 9F, FontStyle.Bold);
        startServiceButton.Location = new Point(100, 12);
        startServiceButton.Size = new Size(84, 30);
        startServiceButton.FlatAppearance.BorderSize = 0;
        startServiceButton.Text = "Start";
        startServiceButton.UseVisualStyleBackColor = false;
        startServiceButton.Click += startServiceButton_Click;
        stopServiceButton.BackColor = Color.FromArgb(185, 65, 65);
        stopServiceButton.Enabled = false;
        stopServiceButton.FlatStyle = FlatStyle.Flat;
        stopServiceButton.ForeColor = Color.White;
        stopServiceButton.Font = new Font("Consolas", 9F, FontStyle.Bold);
        stopServiceButton.Location = new Point(194, 12);
        stopServiceButton.Size = new Size(84, 30);
        stopServiceButton.FlatAppearance.BorderSize = 0;
        stopServiceButton.Text = "Stop";
        stopServiceButton.UseVisualStyleBackColor = false;
        stopServiceButton.Click += stopServiceButton_Click;
        servicesStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        servicesStatusLabel.Font = new Font("Segoe UI", 9.5F);
        servicesStatusLabel.ForeColor = Color.FromArgb(148, 163, 184);
        servicesStatusLabel.Location = new Point(294, 14);
        servicesStatusLabel.Size = new Size(840, 24);
        servicesStatusLabel.Text = "Reading services...";
        servicesStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        callsGrid.AllowUserToAddRows = false;
        callsGrid.AllowUserToDeleteRows = false;
        callsGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        callsGrid.BackgroundColor = Color.FromArgb(15, 22, 30);
        callsGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        callsGrid.Columns.Add("CallTime", "Time");
        callsGrid.Columns.Add("CallArea", "Area");
        callsGrid.Columns.Add("CallAction", "Action");
        callsGrid.Columns.Add("CallDetails", "Details");
        callsGrid.Dock = DockStyle.Fill;
        callsGrid.EnableHeadersVisualStyles = false;
        callsGrid.DefaultCellStyle.BackColor = Color.FromArgb(18, 24, 32);
        callsGrid.DefaultCellStyle.ForeColor = Color.FromArgb(226, 232, 240);
        callsGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(30, 64, 100);
        callsGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(241, 245, 249);
        callsGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(28, 37, 49);
        callsGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(203, 213, 225);
        callsGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        callsGrid.Font = new Font("Segoe UI", 9.25F);
        callsGrid.GridColor = Color.FromArgb(51, 65, 85);
        callsGrid.MultiSelect = false;
        callsGrid.ReadOnly = true;
        callsGrid.RowHeadersVisible = false;
        callsGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        callsToolbarPanel.Controls.Add(clearCallsButton);
        callsToolbarPanel.Controls.Add(callsStatusLabel);
        callsToolbarPanel.BackColor = Color.FromArgb(15, 22, 30);
        callsToolbarPanel.Dock = DockStyle.Top;
        callsToolbarPanel.Height = 54;
        clearCallsButton.BackColor = Color.FromArgb(71, 85, 105);
        clearCallsButton.FlatStyle = FlatStyle.Flat;
        clearCallsButton.ForeColor = Color.White;
        clearCallsButton.Font = new Font("Consolas", 9F, FontStyle.Bold);
        clearCallsButton.Location = new Point(0, 12);
        clearCallsButton.Size = new Size(90, 30);
        clearCallsButton.FlatAppearance.BorderSize = 0;
        clearCallsButton.Text = "Clear";
        clearCallsButton.UseVisualStyleBackColor = false;
        clearCallsButton.Click += clearCallsButton_Click;
        callsStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        callsStatusLabel.Font = new Font("Segoe UI", 9.5F);
        callsStatusLabel.ForeColor = Color.FromArgb(148, 163, 184);
        callsStatusLabel.Location = new Point(110, 14);
        callsStatusLabel.Size = new Size(1100, 24);
        callsStatusLabel.Text = "Application activity and future API calls will appear here.";
        callsStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        processContextMenu.Items.AddRange([endTaskToolStripMenuItem, openFileLocationToolStripMenuItem]);
        processContextMenu.BackColor = Color.FromArgb(20, 27, 35);
        processContextMenu.ForeColor = Color.FromArgb(226, 232, 240);
        endTaskToolStripMenuItem.Text = "End Task";
        endTaskToolStripMenuItem.Click += endTaskButton_Click;
        openFileLocationToolStripMenuItem.Text = "Open File Location";
        openFileLocationToolStripMenuItem.Click += openFileLocationToolStripMenuItem_Click;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(17, 24, 39);
        ClientSize = new Size(1280, 760);
        Controls.Add(mainTabControl);
        Controls.Add(tabHeaderPanel);
        Controls.Add(mainMenuStrip);
        MainMenuStrip = mainMenuStrip;
        MinimumSize = new Size(980, 620);
        StartPosition = FormStartPosition.CenterScreen;
        WindowState = FormWindowState.Maximized;
        Text = "TaskManager";
        mainTabControl.ResumeLayout(false);
        processesTabPage.ResumeLayout(false);
        startupTabPage.ResumeLayout(false);
        servicesTabPage.ResumeLayout(false);
        callsTabPage.ResumeLayout(false);
        processesSplitContainer.Panel1.ResumeLayout(false);
        processesSplitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)processesSplitContainer).EndInit();
        processesSplitContainer.ResumeLayout(false);
        processToolbarPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)processGrid).EndInit();
        processDetailsGroup.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)startupGrid).EndInit();
        startupToolbarPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)servicesGrid).EndInit();
        servicesToolbarPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)callsGrid).EndInit();
        callsToolbarPanel.ResumeLayout(false);
        processContextMenu.ResumeLayout(false);
        mainMenuStrip.ResumeLayout(false);
        mainMenuStrip.PerformLayout();
        tabHeaderPanel.ResumeLayout(false);
        ResumeLayout(false);
        PerformLayout();
    }

    private void AddDetailRow(int rowIndex, string labelText, out Label valueLabel)
    {
        var rowPanel = new Panel
        {
            BackColor = Color.FromArgb(15, 22, 30),
            Dock = DockStyle.Fill,
            Margin = new Padding(0, 0, 0, 8),
            Padding = new Padding(10, 6, 10, 6)
        };

        var titleLabel = new Label
        {
            Dock = DockStyle.Top,
            Font = new Font("Segoe UI", 8F, FontStyle.Bold),
            ForeColor = Color.FromArgb(120, 136, 153),
            Height = 16,
            Text = labelText.ToUpperInvariant(),
            Margin = new Padding(0),
            TextAlign = ContentAlignment.MiddleLeft
        };

        valueLabel = new Label
        {
            Dock = DockStyle.Fill,
            Font = rowIndex == 5 ? new Font("Consolas", 8.75F) : new Font("Segoe UI Semibold", 10F, FontStyle.Bold),
            ForeColor = Color.FromArgb(226, 232, 240),
            Margin = new Padding(0),
            Text = "-",
            AutoEllipsis = true,
            TextAlign = rowIndex == 5 ? ContentAlignment.TopLeft : ContentAlignment.MiddleLeft
        };

        rowPanel.Controls.Add(valueLabel);
        rowPanel.Controls.Add(titleLabel);
        detailsTableLayoutPanel.Controls.Add(rowPanel, 0, rowIndex);
    }
}

