namespace TaskManager;

partial class Form1
{
    private System.ComponentModel.IContainer components = null!;
    private TabControl mainTabControl = null!;
    private TabPage processesTabPage = null!;
    private TabPage processHistoryTabPage = null!;
    private TabPage startupTabPage = null!;
    private TabPage tasksTabPage = null!;
    private TabPage servicesTabPage = null!;
    private TabPage conTabPage = null!;
    private SplitContainer processesSplitContainer = null!;
    private TreeView processTreeView = null!;
    private DataGridView processGrid = null!;
    private Panel processToolbarPanel = null!;
    private DataGridView processHistoryGrid = null!;
    private Panel processHistoryToolbarPanel = null!;
    private Label processHistorySearchLabel = null!;
    private TextBox processHistorySearchTextBox = null!;
    private Label processHistoryStatusLabel = null!;
    private Button refreshProcessesButton = null!;
    private Button endTaskButton = null!;
    private Label processSearchLabel = null!;
    private TextBox processSearchTextBox = null!;
    private Label processStatusLabel = null!;
    private Panel processDetailsPanel = null!;
    private Panel processDetailsHeaderPanel = null!;
    private Label processDetailsHeaderLabel = null!;
    private Panel processDetailsHeaderDivider = null!;
    private TableLayoutPanel detailsTableLayoutPanel = null!;
    private Label detailsNameValueLabel = null!;
    private Label detailsPidValueLabel = null!;
    private Label detailsParentValueLabel = null!;
    private Label detailsStatusValueLabel = null!;
    private Label detailsMemoryValueLabel = null!;
    private Label detailsPathValueLabel = null!;
    private Label securityDetailsLabel = null!;
    private RichTextBox securityDetailsTextBox = null!;
    private DataGridView startupGrid = null!;
    private Panel startupToolbarPanel = null!;
    private Button refreshStartupButton = null!;
    private Label startupStatusLabel = null!;
    private DataGridView tasksGrid = null!;
    private Panel tasksToolbarPanel = null!;
    private Button refreshTasksButton = null!;
    private Label tasksStatusLabel = null!;
    private DataGridView servicesGrid = null!;
    private Panel servicesToolbarPanel = null!;
    private Button refreshServicesButton = null!;
    private Button startServiceButton = null!;
    private Button stopServiceButton = null!;
    private Label servicesStatusLabel = null!;
    private DataGridView callsGrid = null!;
    private Panel callsToolbarPanel = null!;
    private Button clearCallsButton = null!;
    private Label callsStatusLabel = null!;
    private ContextMenuStrip processContextMenu = null!;
    private ToolStripMenuItem endTaskToolStripMenuItem = null!;
    private ToolStripMenuItem openFileLocationToolStripMenuItem = null!;
    private MenuStrip mainMenuStrip = null!;
    private ToolStripMenuItem fileToolStripMenuItem = null!;
    private ToolStripMenuItem refreshProcessesToolStripMenuItem = null!;
    private ToolStripMenuItem refreshStartupToolStripMenuItem = null!;
    private ToolStripMenuItem refreshServicesToolStripMenuItem = null!;
    private ToolStripSeparator fileMenuSeparator1 = null!;
    private ToolStripMenuItem endTaskMenuToolStripMenuItem = null!;
    private Panel tabHeaderPanel = null!;
    private Button processesTabButton = null!;
    private Button processHistoryTabButton = null!;
    private Button startupTabButton = null!;
    private Button tasksTabButton = null!;
    private Button servicesTabButton = null!;
    private Button conTabButton = null!;

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        mainTabControl = new BorderlessTabControl();
        processesTabPage = new TabPage();
        processHistoryTabPage = new TabPage();
        startupTabPage = new TabPage();
        tasksTabPage = new TabPage();
        servicesTabPage = new TabPage();
        conTabPage = new TabPage();
        processesSplitContainer = new SplitContainer();
        processTreeView = new TreeView();
        processGrid = new DataGridView();
        processToolbarPanel = new Panel();
        processHistoryGrid = new DataGridView();
        processHistoryToolbarPanel = new Panel();
        processHistorySearchLabel = new Label();
        processHistorySearchTextBox = new TextBox();
        processHistoryStatusLabel = new Label();
        refreshProcessesButton = new Button();
        endTaskButton = new Button();
        processSearchLabel = new Label();
        processSearchTextBox = new TextBox();
        processStatusLabel = new Label();
        processDetailsPanel = new Panel();
        processDetailsHeaderPanel = new Panel();
        processDetailsHeaderLabel = new Label();
        processDetailsHeaderDivider = new Panel();
        detailsTableLayoutPanel = new TableLayoutPanel();
        securityDetailsLabel = new Label();
        securityDetailsTextBox = new RichTextBox();
        startupGrid = new DataGridView();
        startupToolbarPanel = new Panel();
        refreshStartupButton = new Button();
        startupStatusLabel = new Label();
        tasksGrid = new DataGridView();
        tasksToolbarPanel = new Panel();
        refreshTasksButton = new Button();
        tasksStatusLabel = new Label();
        servicesGrid = new DataGridView();
        servicesToolbarPanel = new Panel();
        refreshServicesButton = new Button();
        startServiceButton = new Button();
        stopServiceButton = new Button();
        servicesStatusLabel = new Label();
        callsGrid = new DataGridView();
        callsToolbarPanel = new Panel();
        clearCallsButton = new Button();
        callsStatusLabel = new Label();
        processContextMenu = new ContextMenuStrip(components);
        endTaskToolStripMenuItem = new ToolStripMenuItem();
        openFileLocationToolStripMenuItem = new ToolStripMenuItem();
        mainMenuStrip = new MenuStrip();
        fileToolStripMenuItem = new ToolStripMenuItem();
        refreshProcessesToolStripMenuItem = new ToolStripMenuItem();
        refreshStartupToolStripMenuItem = new ToolStripMenuItem();
        refreshServicesToolStripMenuItem = new ToolStripMenuItem();
        fileMenuSeparator1 = new ToolStripSeparator();
        endTaskMenuToolStripMenuItem = new ToolStripMenuItem();
        tabHeaderPanel = new Panel();
        processesTabButton = new Button();
        processHistoryTabButton = new Button();
        startupTabButton = new Button();
        tasksTabButton = new Button();
        servicesTabButton = new Button();
        conTabButton = new Button();
        mainTabControl.SuspendLayout();
        processesTabPage.SuspendLayout();
        processHistoryTabPage.SuspendLayout();
        startupTabPage.SuspendLayout();
        tasksTabPage.SuspendLayout();
        servicesTabPage.SuspendLayout();
        conTabPage.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)processesSplitContainer).BeginInit();
        processesSplitContainer.Panel1.SuspendLayout();
        processesSplitContainer.Panel2.SuspendLayout();
        processesSplitContainer.SuspendLayout();
        processToolbarPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)processGrid).BeginInit();
        ((System.ComponentModel.ISupportInitialize)processHistoryGrid).BeginInit();
        processHistoryToolbarPanel.SuspendLayout();
        processDetailsPanel.SuspendLayout();
        processDetailsHeaderPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)startupGrid).BeginInit();
        startupToolbarPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)tasksGrid).BeginInit();
        tasksToolbarPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)servicesGrid).BeginInit();
        servicesToolbarPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)callsGrid).BeginInit();
        callsToolbarPanel.SuspendLayout();
        processContextMenu.SuspendLayout();
        mainMenuStrip.SuspendLayout();
        tabHeaderPanel.SuspendLayout();
        SuspendLayout();
        mainMenuStrip.Items.AddRange([fileToolStripMenuItem]);
        mainMenuStrip.BackColor = Color.FromArgb(34, 29, 37);
        mainMenuStrip.Dock = DockStyle.Top;
        mainMenuStrip.ForeColor = Color.FromArgb(226, 226, 230);
        mainMenuStrip.Font = new Font("Segoe UI", 9F);
        mainMenuStrip.Padding = new Padding(8, 2, 0, 2);
        fileToolStripMenuItem.DropDownItems.AddRange([refreshProcessesToolStripMenuItem, refreshStartupToolStripMenuItem, refreshServicesToolStripMenuItem, fileMenuSeparator1, endTaskMenuToolStripMenuItem]);
        fileToolStripMenuItem.Text = "File";
        refreshProcessesToolStripMenuItem.Text = "Refresh Processes";
        refreshProcessesToolStripMenuItem.Click += refreshProcessesButton_Click;
        refreshStartupToolStripMenuItem.Text = "Refresh Startup";
        refreshStartupToolStripMenuItem.Click += refreshStartupButton_Click;
        refreshServicesToolStripMenuItem.Text = "Refresh Services";
        refreshServicesToolStripMenuItem.Click += refreshServicesButton_Click;
        endTaskMenuToolStripMenuItem.Text = "End Task";
        endTaskMenuToolStripMenuItem.Click += endTaskButton_Click;
        tabHeaderPanel.Controls.Add(processHistoryTabButton);
        tabHeaderPanel.Controls.Add(conTabButton);
        tabHeaderPanel.Controls.Add(servicesTabButton);
        tabHeaderPanel.Controls.Add(tasksTabButton);
        tabHeaderPanel.Controls.Add(startupTabButton);
        tabHeaderPanel.Controls.Add(processesTabButton);
        tabHeaderPanel.BackColor = Color.FromArgb(25, 25, 25);
        tabHeaderPanel.Dock = DockStyle.Top;
        tabHeaderPanel.Height = 40;
        processesTabButton.BackColor = Color.FromArgb(39, 39, 39);
        processesTabButton.FlatAppearance.BorderColor = Color.FromArgb(39, 39, 39);
        processesTabButton.FlatAppearance.BorderSize = 0;
        processesTabButton.FlatStyle = FlatStyle.Flat;
        processesTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        processesTabButton.ForeColor = Color.FromArgb(245, 245, 245);
        processesTabButton.Location = new Point(0, 5);
        processesTabButton.Size = new Size(84, 30);
        processesTabButton.Text = "Processes";
        processesTabButton.UseVisualStyleBackColor = false;
        processesTabButton.Click += processesTabButton_Click;
        processHistoryTabButton.BackColor = Color.FromArgb(25, 25, 25);
        processHistoryTabButton.FlatAppearance.BorderColor = Color.FromArgb(25, 25, 25);
        processHistoryTabButton.FlatAppearance.BorderSize = 0;
        processHistoryTabButton.FlatStyle = FlatStyle.Flat;
        processHistoryTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        processHistoryTabButton.ForeColor = Color.FromArgb(170, 170, 175);
        processHistoryTabButton.Location = new Point(86, 5);
        processHistoryTabButton.Size = new Size(116, 30);
        processHistoryTabButton.Text = "Process History";
        processHistoryTabButton.UseVisualStyleBackColor = false;
        processHistoryTabButton.Click += processHistoryTabButton_Click;
        startupTabButton.BackColor = Color.FromArgb(25, 25, 25);
        startupTabButton.FlatAppearance.BorderColor = Color.FromArgb(25, 25, 25);
        startupTabButton.FlatAppearance.BorderSize = 0;
        startupTabButton.FlatStyle = FlatStyle.Flat;
        startupTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        startupTabButton.ForeColor = Color.FromArgb(170, 170, 175);
        startupTabButton.Location = new Point(204, 5);
        startupTabButton.Size = new Size(66, 30);
        startupTabButton.Text = "Startup";
        startupTabButton.UseVisualStyleBackColor = false;
        startupTabButton.Click += startupTabButton_Click;
        tasksTabButton.BackColor = Color.FromArgb(25, 25, 25);
        tasksTabButton.FlatAppearance.BorderColor = Color.FromArgb(25, 25, 25);
        tasksTabButton.FlatAppearance.BorderSize = 0;
        tasksTabButton.FlatStyle = FlatStyle.Flat;
        tasksTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        tasksTabButton.ForeColor = Color.FromArgb(170, 170, 175);
        tasksTabButton.Location = new Point(272, 5);
        tasksTabButton.Size = new Size(110, 30);
        tasksTabButton.Text = "Task Scheduler";
        tasksTabButton.UseVisualStyleBackColor = false;
        tasksTabButton.Click += tasksTabButton_Click;
        servicesTabButton.BackColor = Color.FromArgb(25, 25, 25);
        servicesTabButton.FlatAppearance.BorderColor = Color.FromArgb(25, 25, 25);
        servicesTabButton.FlatAppearance.BorderSize = 0;
        servicesTabButton.FlatStyle = FlatStyle.Flat;
        servicesTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        servicesTabButton.ForeColor = Color.FromArgb(170, 170, 175);
        servicesTabButton.Location = new Point(384, 5);
        servicesTabButton.Size = new Size(70, 30);
        servicesTabButton.Text = "Services";
        servicesTabButton.UseVisualStyleBackColor = false;
        servicesTabButton.Click += servicesTabButton_Click;
        conTabButton.BackColor = Color.FromArgb(25, 25, 25);
        conTabButton.FlatAppearance.BorderColor = Color.FromArgb(25, 25, 25);
        conTabButton.FlatAppearance.BorderSize = 0;
        conTabButton.FlatStyle = FlatStyle.Flat;
        conTabButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        conTabButton.ForeColor = Color.FromArgb(170, 170, 175);
        conTabButton.Location = new Point(456, 5);
        conTabButton.Size = new Size(74, 30);
        conTabButton.Text = "Network";
        conTabButton.UseVisualStyleBackColor = false;
        conTabButton.Click += conTabButton_Click;
        mainTabControl.Controls.Add(processesTabPage);
        mainTabControl.Controls.Add(processHistoryTabPage);
        mainTabControl.Controls.Add(startupTabPage);
        mainTabControl.Controls.Add(tasksTabPage);
        mainTabControl.Controls.Add(servicesTabPage);
        mainTabControl.Controls.Add(conTabPage);
        mainTabControl.Dock = DockStyle.Fill;
        mainTabControl.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        mainTabControl.ItemSize = new Size(0, 1);
        mainTabControl.Padding = new Point(0, 0);
        mainTabControl.SelectedIndex = 0;
        mainTabControl.Size = new Size(1280, 760);
        mainTabControl.SizeMode = TabSizeMode.Fixed;
        mainTabControl.BackColor = Color.FromArgb(25, 25, 25);
        mainTabControl.SelectedIndexChanged += mainTabControl_SelectedIndexChanged;
        processesTabPage.BackColor = Color.FromArgb(25, 25, 25);
        processesTabPage.Controls.Add(processesSplitContainer);
        processesTabPage.Controls.Add(processToolbarPanel);
        processesTabPage.Padding = new Padding(8);
        processesTabPage.Text = "Processes";
        processHistoryTabPage.BackColor = Color.FromArgb(25, 25, 25);
        processHistoryTabPage.Controls.Add(processHistoryGrid);
        processHistoryTabPage.Controls.Add(processHistoryToolbarPanel);
        processHistoryTabPage.Padding = new Padding(8);
        processHistoryTabPage.Text = "Process History";
        startupTabPage.BackColor = Color.FromArgb(25, 25, 25);
        startupTabPage.Controls.Add(startupGrid);
        startupTabPage.Controls.Add(startupToolbarPanel);
        startupTabPage.Padding = new Padding(8);
        startupTabPage.Text = "Startup";
        tasksTabPage.BackColor = Color.FromArgb(25, 25, 25);
        tasksTabPage.Controls.Add(tasksGrid);
        tasksTabPage.Controls.Add(tasksToolbarPanel);
        tasksTabPage.Padding = new Padding(8);
        tasksTabPage.Text = "Task Scheduler";
        servicesTabPage.BackColor = Color.FromArgb(25, 25, 25);
        servicesTabPage.Controls.Add(servicesGrid);
        servicesTabPage.Controls.Add(servicesToolbarPanel);
        servicesTabPage.Padding = new Padding(8);
        servicesTabPage.Text = "Services";
        conTabPage.BackColor = Color.FromArgb(25, 25, 25);
        conTabPage.Controls.Add(callsGrid);
        conTabPage.Controls.Add(callsToolbarPanel);
        conTabPage.Padding = new Padding(8);
        conTabPage.Text = "Network";
        processesSplitContainer.Dock = DockStyle.Fill;
        processesSplitContainer.FixedPanel = FixedPanel.Panel2;
        processesSplitContainer.Location = new Point(8, 62);
        processesSplitContainer.SplitterWidth = 2;
        processesSplitContainer.Panel1.Controls.Add(processGrid);
        processesSplitContainer.Panel2.Controls.Add(processDetailsPanel);
        processesSplitContainer.BackColor = Color.FromArgb(49, 49, 49);
        processGrid.AllowUserToAddRows = false;
        processGrid.AllowUserToDeleteRows = false;
        processGrid.AllowUserToOrderColumns = true;
        processGrid.AllowUserToResizeColumns = true;
        processGrid.AllowUserToResizeRows = false;
        processGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        processGrid.BackgroundColor = Color.FromArgb(25, 25, 25);
        processGrid.BorderStyle = BorderStyle.None;
        processGrid.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
        processGrid.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
        processGrid.ColumnHeadersHeight = 48;
        processGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        processGrid.Dock = DockStyle.Fill;
        processGrid.EnableHeadersVisualStyles = false;
        processGrid.GridColor = Color.FromArgb(49, 49, 49);
        processGrid.MultiSelect = false;
        processGrid.ReadOnly = true;
        processGrid.RowHeadersVisible = false;
        processGrid.RowTemplate.Height = 28;
        processGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        processGrid.BackgroundColor = Color.FromArgb(25, 25, 25);
        processGrid.DefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        processGrid.DefaultCellStyle.ForeColor = Color.FromArgb(243, 243, 243);
        processGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(38, 34, 56);
        processGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(245, 245, 245);
        processGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        processGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(232, 232, 232);
        processGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 9F);
        processGrid.ColumnHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(25, 25, 25);
        processGrid.ColumnHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(232, 232, 232);
        processGrid.Font = new Font("Segoe UI", 9F);
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "NameColumn", HeaderText = "Name", Width = 330, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "ProcessNameColumn", HeaderText = "Process name", Width = 140, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "PidColumn", HeaderText = "PID", Width = 70, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "CpuColumn", HeaderText = "CPU", Width = 70, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "MemoryColumn", HeaderText = "Memory", Width = 90, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "GpuColumn", HeaderText = "GPU", Width = 70, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "DiskColumn", HeaderText = "Disk", Width = 70, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "NetworkColumn", HeaderText = "Network", Width = 80, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "StatusColumn", HeaderText = "Status", Width = 100, SortMode = DataGridViewColumnSortMode.Programmatic });
        processGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "CommandLineColumn", HeaderText = "Command line", Width = 360, MinimumWidth = 360, AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill, FillWeight = 100F, SortMode = DataGridViewColumnSortMode.Programmatic });
        processToolbarPanel.Controls.Add(processSearchTextBox);
        processToolbarPanel.Controls.Add(processSearchLabel);
        processToolbarPanel.Controls.Add(processStatusLabel);
        processToolbarPanel.BackColor = Color.FromArgb(25, 25, 25);
        processToolbarPanel.Dock = DockStyle.Top;
        processToolbarPanel.Height = 54;
        processHistoryGrid.AllowUserToAddRows = false;
        processHistoryGrid.AllowUserToDeleteRows = false;
        processHistoryGrid.AllowUserToResizeColumns = true;
        processHistoryGrid.AllowUserToResizeRows = false;
        processHistoryGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
        processHistoryGrid.BackgroundColor = Color.FromArgb(25, 25, 25);
        processHistoryGrid.BorderStyle = BorderStyle.None;
        processHistoryGrid.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
        processHistoryGrid.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
        processHistoryGrid.ColumnHeadersHeight = 48;
        processHistoryGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        processHistoryGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "HistoryName", HeaderText = "Name", Width = 210 });
        processHistoryGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "HistoryProcessName", HeaderText = "Process name", Width = 140 });
        processHistoryGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "HistoryPid", HeaderText = "PID", Width = 72 });
        processHistoryGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "HistoryStarted", HeaderText = "Started", Width = 150 });
        processHistoryGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "HistoryClosed", HeaderText = "Closed", Width = 150 });
        processHistoryGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "HistoryStatus", HeaderText = "Status", Width = 90 });
        processHistoryGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "HistoryPath", HeaderText = "Path", Width = 300 });
        processHistoryGrid.Columns.Add(new DataGridViewTextBoxColumn { Name = "HistoryCommandLine", HeaderText = "Command line", Width = 360, MinimumWidth = 360, AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill, FillWeight = 100F });
        processHistoryGrid.DefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        processHistoryGrid.DefaultCellStyle.ForeColor = Color.FromArgb(243, 243, 243);
        processHistoryGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(38, 34, 56);
        processHistoryGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(245, 245, 245);
        processHistoryGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        processHistoryGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(232, 232, 232);
        processHistoryGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 9F);
        processHistoryGrid.ColumnHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(25, 25, 25);
        processHistoryGrid.ColumnHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(232, 232, 232);
        processHistoryGrid.Dock = DockStyle.Fill;
        processHistoryGrid.EnableHeadersVisualStyles = false;
        processHistoryGrid.Font = new Font("Segoe UI", 9F);
        processHistoryGrid.GridColor = Color.FromArgb(49, 49, 49);
        processHistoryGrid.MultiSelect = false;
        processHistoryGrid.ReadOnly = true;
        processHistoryGrid.RowHeadersVisible = false;
        processHistoryGrid.RowTemplate.Height = 28;
        processHistoryGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        processHistoryToolbarPanel.Controls.Add(processHistorySearchTextBox);
        processHistoryToolbarPanel.Controls.Add(processHistorySearchLabel);
        processHistoryToolbarPanel.Controls.Add(processHistoryStatusLabel);
        processHistoryToolbarPanel.BackColor = Color.FromArgb(25, 25, 25);
        processHistoryToolbarPanel.Dock = DockStyle.Top;
        processHistoryToolbarPanel.Height = 54;
        processHistorySearchLabel.Font = new Font("Segoe UI", 9F, FontStyle.Regular);
        processHistorySearchLabel.ForeColor = Color.FromArgb(170, 170, 175);
        processHistorySearchLabel.Location = new Point(0, 16);
        processHistorySearchLabel.Size = new Size(48, 20);
        processHistorySearchLabel.Text = "Search";
        processHistorySearchTextBox.BackColor = Color.FromArgb(47, 43, 52);
        processHistorySearchTextBox.BorderStyle = BorderStyle.None;
        processHistorySearchTextBox.Font = new Font("Segoe UI", 9.25F);
        processHistorySearchTextBox.ForeColor = Color.FromArgb(232, 232, 232);
        processHistorySearchTextBox.Location = new Point(64, 15);
        processHistorySearchTextBox.Size = new Size(360, 20);
        processHistorySearchTextBox.TextChanged += processHistorySearchTextBox_TextChanged;
        processHistoryStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        processHistoryStatusLabel.Font = new Font("Segoe UI", 9F);
        processHistoryStatusLabel.ForeColor = Color.FromArgb(170, 170, 175);
        processHistoryStatusLabel.Location = new Point(440, 14);
        processHistoryStatusLabel.Size = new Size(742, 24);
        processHistoryStatusLabel.Text = "Process history will populate while TaskManager is running.";
        processHistoryStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        refreshProcessesButton.BackColor = Color.FromArgb(52, 52, 52);
        refreshProcessesButton.FlatStyle = FlatStyle.Flat;
        refreshProcessesButton.ForeColor = Color.White;
        refreshProcessesButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        refreshProcessesButton.Location = new Point(0, 12);
        refreshProcessesButton.Size = new Size(90, 30);
        refreshProcessesButton.FlatAppearance.BorderSize = 0;
        refreshProcessesButton.Text = "Refresh";
        refreshProcessesButton.UseVisualStyleBackColor = false;
        refreshProcessesButton.Visible = false;
        refreshProcessesButton.Click += refreshProcessesButton_Click;
        endTaskButton.BackColor = Color.FromArgb(185, 65, 65);
        endTaskButton.Enabled = false;
        endTaskButton.FlatStyle = FlatStyle.Flat;
        endTaskButton.ForeColor = Color.White;
        endTaskButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        endTaskButton.Location = new Point(100, 12);
        endTaskButton.Size = new Size(90, 30);
        endTaskButton.FlatAppearance.BorderSize = 0;
        endTaskButton.Text = "End Task";
        endTaskButton.UseVisualStyleBackColor = false;
        endTaskButton.Visible = false;
        endTaskButton.Click += endTaskButton_Click;
        processSearchLabel.Font = new Font("Segoe UI", 9F, FontStyle.Regular);
        processSearchLabel.ForeColor = Color.FromArgb(170, 170, 175);
        processSearchLabel.Location = new Point(0, 16);
        processSearchLabel.Size = new Size(48, 20);
        processSearchLabel.Text = "Search";
        processSearchTextBox.BackColor = Color.FromArgb(47, 43, 52);
        processSearchTextBox.BorderStyle = BorderStyle.None;
        processSearchTextBox.Font = new Font("Segoe UI", 9.25F);
        processSearchTextBox.ForeColor = Color.FromArgb(232, 232, 232);
        processSearchTextBox.Location = new Point(64, 15);
        processSearchTextBox.Size = new Size(360, 20);
        processSearchTextBox.TextChanged += processSearchTextBox_TextChanged;
        processStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        processStatusLabel.Font = new Font("Segoe UI", 9F);
        processStatusLabel.ForeColor = Color.FromArgb(170, 170, 175);
        processStatusLabel.Location = new Point(440, 14);
        processStatusLabel.Size = new Size(742, 24);
        processStatusLabel.Text = "Reading processes...";
        processStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        processDetailsPanel.BackColor = Color.FromArgb(30, 30, 30);
        processDetailsPanel.Controls.Add(detailsTableLayoutPanel);
        processDetailsPanel.Controls.Add(processDetailsHeaderPanel);
        processDetailsPanel.Dock = DockStyle.Fill;
        processDetailsPanel.Padding = new Padding(10, 0, 10, 10);
        processDetailsHeaderPanel.BackColor = Color.FromArgb(30, 30, 30);
        processDetailsHeaderPanel.Controls.Add(processDetailsHeaderLabel);
        processDetailsHeaderPanel.Controls.Add(processDetailsHeaderDivider);
        processDetailsHeaderPanel.Dock = DockStyle.Top;
        processDetailsHeaderPanel.Height = 42;
        processDetailsHeaderLabel.BackColor = Color.FromArgb(30, 30, 30);
        processDetailsHeaderLabel.Dock = DockStyle.Fill;
        processDetailsHeaderLabel.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        processDetailsHeaderLabel.ForeColor = Color.FromArgb(228, 228, 228);
        processDetailsHeaderLabel.Text = "Selected Process";
        processDetailsHeaderLabel.TextAlign = ContentAlignment.MiddleLeft;
        processDetailsHeaderDivider.BackColor = Color.FromArgb(49, 49, 49);
        processDetailsHeaderDivider.Dock = DockStyle.Bottom;
        processDetailsHeaderDivider.Height = 1;
        detailsTableLayoutPanel.ColumnCount = 1;
        detailsTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        detailsTableLayoutPanel.Dock = DockStyle.Fill;
        detailsTableLayoutPanel.BackColor = Color.FromArgb(30, 30, 30);
        detailsTableLayoutPanel.RowCount = 8;
        detailsTableLayoutPanel.Padding = new Padding(0, 8, 0, 0);
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 64F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        detailsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        AddDetailRow(0, "Name", out detailsNameValueLabel);
        AddDetailRow(1, "PID", out detailsPidValueLabel);
        AddDetailRow(2, "Parent PID", out detailsParentValueLabel);
        AddDetailRow(3, "Status", out detailsStatusValueLabel);
        AddDetailRow(4, "Memory", out detailsMemoryValueLabel);
        AddDetailRow(5, "Path", out detailsPathValueLabel);
        securityDetailsLabel.Dock = DockStyle.Fill;
        securityDetailsLabel.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        securityDetailsLabel.ForeColor = Color.FromArgb(170, 170, 175);
        securityDetailsLabel.Text = "Security";
        securityDetailsLabel.TextAlign = ContentAlignment.MiddleLeft;
        detailsTableLayoutPanel.Controls.Add(securityDetailsLabel, 0, 6);
        securityDetailsTextBox.BackColor = Color.FromArgb(25, 25, 25);
        securityDetailsTextBox.BorderStyle = BorderStyle.None;
        securityDetailsTextBox.Dock = DockStyle.Fill;
        securityDetailsTextBox.Font = new Font("Consolas", 9F);
        securityDetailsTextBox.ForeColor = Color.FromArgb(226, 232, 240);
        securityDetailsTextBox.Margin = new Padding(0);
        securityDetailsTextBox.ReadOnly = true;
        securityDetailsTextBox.ScrollBars = RichTextBoxScrollBars.Vertical;
        securityDetailsTextBox.Text = "Select a process to inspect binary details.";
        detailsTableLayoutPanel.Controls.Add(securityDetailsTextBox, 0, 7);
        startupGrid.AllowUserToAddRows = false;
        startupGrid.AllowUserToDeleteRows = false;
        startupGrid.AllowUserToResizeColumns = true;
        startupGrid.AllowUserToResizeRows = false;
        startupGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        startupGrid.BackgroundColor = Color.FromArgb(25, 25, 25);
        startupGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        startupGrid.Columns.Add("StartupName", "Name");
        startupGrid.Columns.Add("StartupScope", "Scope");
        startupGrid.Columns.Add("StartupType", "Type");
        startupGrid.Columns.Add("StartupLastRun", "Last run");
        startupGrid.Columns.Add("StartupNextRun", "Next execution");
        startupGrid.Columns.Add("StartupLocation", "Location");
        startupGrid.Columns.Add("StartupCommand", "Command");
        startupGrid.Dock = DockStyle.Fill;
        startupGrid.EnableHeadersVisualStyles = false;
        startupGrid.DefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        startupGrid.DefaultCellStyle.ForeColor = Color.FromArgb(243, 243, 243);
        startupGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(38, 34, 56);
        startupGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(245, 245, 245);
        startupGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        startupGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(232, 232, 232);
        startupGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 9F);
        startupGrid.Font = new Font("Segoe UI", 9F);
        startupGrid.GridColor = Color.FromArgb(49, 49, 49);
        startupGrid.MultiSelect = false;
        startupGrid.ReadOnly = true;
        startupGrid.RowHeadersVisible = false;
        startupGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        startupToolbarPanel.Controls.Add(refreshStartupButton);
        startupToolbarPanel.Controls.Add(startupStatusLabel);
        startupToolbarPanel.BackColor = Color.FromArgb(25, 25, 25);
        startupToolbarPanel.Dock = DockStyle.Top;
        startupToolbarPanel.Height = 54;
        refreshStartupButton.BackColor = Color.FromArgb(52, 52, 52);
        refreshStartupButton.FlatStyle = FlatStyle.Flat;
        refreshStartupButton.ForeColor = Color.White;
        refreshStartupButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        refreshStartupButton.Location = new Point(0, 12);
        refreshStartupButton.Size = new Size(90, 30);
        refreshStartupButton.FlatAppearance.BorderSize = 0;
        refreshStartupButton.Text = "Refresh";
        refreshStartupButton.UseVisualStyleBackColor = false;
        refreshStartupButton.Click += refreshStartupButton_Click;
        startupStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        startupStatusLabel.Font = new Font("Segoe UI", 9F);
        startupStatusLabel.ForeColor = Color.FromArgb(170, 170, 175);
        startupStatusLabel.Location = new Point(110, 14);
        startupStatusLabel.Size = new Size(1100, 24);
        startupStatusLabel.Text = "Reading startup items...";
        startupStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        tasksGrid.AllowUserToAddRows = false;
        tasksGrid.AllowUserToDeleteRows = false;
        tasksGrid.AllowUserToResizeColumns = true;
        tasksGrid.AllowUserToResizeRows = false;
        tasksGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        tasksGrid.BackgroundColor = Color.FromArgb(25, 25, 25);
        tasksGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        tasksGrid.Columns.Add("TaskName", "Name");
        tasksGrid.Columns.Add("TaskLastRun", "Last run");
        tasksGrid.Columns.Add("TaskNextRun", "Next run");
        tasksGrid.Columns.Add("TaskCommand", "Command");
        tasksGrid.Dock = DockStyle.Fill;
        tasksGrid.EnableHeadersVisualStyles = false;
        tasksGrid.DefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        tasksGrid.DefaultCellStyle.ForeColor = Color.FromArgb(243, 243, 243);
        tasksGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(38, 34, 56);
        tasksGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(245, 245, 245);
        tasksGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        tasksGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(232, 232, 232);
        tasksGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 9F);
        tasksGrid.Font = new Font("Segoe UI", 9F);
        tasksGrid.GridColor = Color.FromArgb(49, 49, 49);
        tasksGrid.MultiSelect = false;
        tasksGrid.ReadOnly = true;
        tasksGrid.RowHeadersVisible = false;
        tasksGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        tasksToolbarPanel.Controls.Add(refreshTasksButton);
        tasksToolbarPanel.Controls.Add(tasksStatusLabel);
        tasksToolbarPanel.BackColor = Color.FromArgb(25, 25, 25);
        tasksToolbarPanel.Dock = DockStyle.Top;
        tasksToolbarPanel.Height = 54;
        refreshTasksButton.BackColor = Color.FromArgb(52, 52, 52);
        refreshTasksButton.FlatStyle = FlatStyle.Flat;
        refreshTasksButton.ForeColor = Color.White;
        refreshTasksButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        refreshTasksButton.Location = new Point(0, 12);
        refreshTasksButton.Size = new Size(90, 30);
        refreshTasksButton.FlatAppearance.BorderSize = 0;
        refreshTasksButton.Text = "Refresh";
        refreshTasksButton.UseVisualStyleBackColor = false;
        refreshTasksButton.Click += refreshTasksButton_Click;
        tasksStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        tasksStatusLabel.Font = new Font("Segoe UI", 9F);
        tasksStatusLabel.ForeColor = Color.FromArgb(170, 170, 175);
        tasksStatusLabel.Location = new Point(110, 14);
        tasksStatusLabel.Size = new Size(1100, 24);
        tasksStatusLabel.Text = "Reading scheduled tasks...";
        tasksStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        servicesGrid.AllowUserToAddRows = false;
        servicesGrid.AllowUserToDeleteRows = false;
        servicesGrid.AllowUserToResizeColumns = true;
        servicesGrid.AllowUserToResizeRows = false;
        servicesGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        servicesGrid.BackgroundColor = Color.FromArgb(25, 25, 25);
        servicesGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        servicesGrid.Columns.Add("ServiceDisplayName", "Display Name");
        servicesGrid.Columns.Add("ServiceName", "Service Name");
        servicesGrid.Columns.Add("ServiceStatus", "Status");
        servicesGrid.Columns.Add("ServiceStartType", "Start Type");
        servicesGrid.Dock = DockStyle.Fill;
        servicesGrid.EnableHeadersVisualStyles = false;
        servicesGrid.DefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        servicesGrid.DefaultCellStyle.ForeColor = Color.FromArgb(243, 243, 243);
        servicesGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(38, 34, 56);
        servicesGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(245, 245, 245);
        servicesGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        servicesGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(232, 232, 232);
        servicesGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 9F);
        servicesGrid.Font = new Font("Segoe UI", 9F);
        servicesGrid.GridColor = Color.FromArgb(49, 49, 49);
        servicesGrid.MultiSelect = false;
        servicesGrid.ReadOnly = true;
        servicesGrid.RowHeadersVisible = false;
        servicesGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        servicesGrid.SelectionChanged += servicesGrid_SelectionChanged;
        servicesToolbarPanel.Controls.Add(refreshServicesButton);
        servicesToolbarPanel.Controls.Add(startServiceButton);
        servicesToolbarPanel.Controls.Add(stopServiceButton);
        servicesToolbarPanel.Controls.Add(servicesStatusLabel);
        servicesToolbarPanel.BackColor = Color.FromArgb(25, 25, 25);
        servicesToolbarPanel.Dock = DockStyle.Top;
        servicesToolbarPanel.Height = 54;
        refreshServicesButton.BackColor = Color.FromArgb(52, 52, 52);
        refreshServicesButton.FlatStyle = FlatStyle.Flat;
        refreshServicesButton.ForeColor = Color.White;
        refreshServicesButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        refreshServicesButton.Location = new Point(0, 12);
        refreshServicesButton.Size = new Size(90, 30);
        refreshServicesButton.FlatAppearance.BorderSize = 0;
        refreshServicesButton.Text = "Refresh";
        refreshServicesButton.UseVisualStyleBackColor = false;
        refreshServicesButton.Click += refreshServicesButton_Click;
        startServiceButton.BackColor = Color.FromArgb(42, 109, 81);
        startServiceButton.Enabled = false;
        startServiceButton.FlatStyle = FlatStyle.Flat;
        startServiceButton.ForeColor = Color.White;
        startServiceButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        startServiceButton.Location = new Point(100, 12);
        startServiceButton.Size = new Size(84, 30);
        startServiceButton.FlatAppearance.BorderSize = 0;
        startServiceButton.Text = "Start";
        startServiceButton.UseVisualStyleBackColor = false;
        startServiceButton.Click += startServiceButton_Click;
        stopServiceButton.BackColor = Color.FromArgb(185, 65, 65);
        stopServiceButton.Enabled = false;
        stopServiceButton.FlatStyle = FlatStyle.Flat;
        stopServiceButton.ForeColor = Color.White;
        stopServiceButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        stopServiceButton.Location = new Point(194, 12);
        stopServiceButton.Size = new Size(84, 30);
        stopServiceButton.FlatAppearance.BorderSize = 0;
        stopServiceButton.Text = "Stop";
        stopServiceButton.UseVisualStyleBackColor = false;
        stopServiceButton.Click += stopServiceButton_Click;
        servicesStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        servicesStatusLabel.Font = new Font("Segoe UI", 9F);
        servicesStatusLabel.ForeColor = Color.FromArgb(170, 170, 175);
        servicesStatusLabel.Location = new Point(294, 14);
        servicesStatusLabel.Size = new Size(840, 24);
        servicesStatusLabel.Text = "Reading services...";
        servicesStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        callsGrid.AllowUserToAddRows = false;
        callsGrid.AllowUserToDeleteRows = false;
        callsGrid.AllowUserToResizeColumns = true;
        callsGrid.AllowUserToResizeRows = false;
        callsGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        callsGrid.BackgroundColor = Color.FromArgb(25, 25, 25);
        callsGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        callsGrid.Columns.Add("ConnectionBinary", "Process");
        callsGrid.Columns.Add("ConnectionDns", "DNS");
        callsGrid.Columns.Add("ConnectionIp", "IP");
        callsGrid.Columns.Add("ConnectionUpload", "Upload");
        callsGrid.Columns.Add("ConnectionDownload", "Download");
        callsGrid.Dock = DockStyle.Fill;
        callsGrid.EnableHeadersVisualStyles = false;
        callsGrid.DefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        callsGrid.DefaultCellStyle.ForeColor = Color.FromArgb(243, 243, 243);
        callsGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(38, 34, 56);
        callsGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(245, 245, 245);
        callsGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(25, 25, 25);
        callsGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(232, 232, 232);
        callsGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 9F);
        callsGrid.Font = new Font("Segoe UI", 9F);
        callsGrid.GridColor = Color.FromArgb(49, 49, 49);
        callsGrid.MultiSelect = false;
        callsGrid.ReadOnly = true;
        callsGrid.RowHeadersVisible = false;
        callsGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        callsToolbarPanel.Controls.Add(clearCallsButton);
        callsToolbarPanel.Controls.Add(callsStatusLabel);
        callsToolbarPanel.BackColor = Color.FromArgb(25, 25, 25);
        callsToolbarPanel.Dock = DockStyle.Top;
        callsToolbarPanel.Height = 54;
        clearCallsButton.BackColor = Color.FromArgb(52, 52, 52);
        clearCallsButton.FlatStyle = FlatStyle.Flat;
        clearCallsButton.ForeColor = Color.White;
        clearCallsButton.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        clearCallsButton.Location = new Point(0, 12);
        clearCallsButton.Size = new Size(90, 30);
        clearCallsButton.FlatAppearance.BorderSize = 0;
        clearCallsButton.Text = "Clear";
        clearCallsButton.UseVisualStyleBackColor = false;
        clearCallsButton.Click += clearCallsButton_Click;
        callsStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        callsStatusLabel.Font = new Font("Segoe UI", 9F);
        callsStatusLabel.ForeColor = Color.FromArgb(170, 170, 175);
        callsStatusLabel.Location = new Point(110, 14);
        callsStatusLabel.Size = new Size(1100, 24);
        callsStatusLabel.Text = "Connection records will appear here.";
        callsStatusLabel.TextAlign = ContentAlignment.MiddleRight;
        processContextMenu.Items.AddRange([endTaskToolStripMenuItem, openFileLocationToolStripMenuItem]);
        processContextMenu.BackColor = Color.FromArgb(37, 37, 38);
        processContextMenu.ForeColor = Color.FromArgb(238, 238, 238);
        endTaskToolStripMenuItem.Text = "End Task";
        endTaskToolStripMenuItem.Click += endTaskButton_Click;
        openFileLocationToolStripMenuItem.Text = "Open File Location";
        openFileLocationToolStripMenuItem.Click += openFileLocationToolStripMenuItem_Click;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(25, 25, 25);
        ClientSize = new Size(1280, 760);
        Controls.Add(mainTabControl);
        Controls.Add(tabHeaderPanel);
        Controls.Add(mainMenuStrip);
        MainMenuStrip = mainMenuStrip;
        MinimumSize = new Size(980, 620);
        StartPosition = FormStartPosition.CenterScreen;
        WindowState = FormWindowState.Maximized;
        Text = "TaskManager";
        mainTabControl.ResumeLayout(false);
        processesTabPage.ResumeLayout(false);
        processHistoryTabPage.ResumeLayout(false);
        startupTabPage.ResumeLayout(false);
        tasksTabPage.ResumeLayout(false);
        servicesTabPage.ResumeLayout(false);
        conTabPage.ResumeLayout(false);
        processesSplitContainer.Panel1.ResumeLayout(false);
        processesSplitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)processesSplitContainer).EndInit();
        processesSplitContainer.ResumeLayout(false);
        processToolbarPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)processGrid).EndInit();
        ((System.ComponentModel.ISupportInitialize)processHistoryGrid).EndInit();
        processHistoryToolbarPanel.ResumeLayout(false);
        processDetailsHeaderPanel.ResumeLayout(false);
        processDetailsPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)startupGrid).EndInit();
        startupToolbarPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)tasksGrid).EndInit();
        tasksToolbarPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)servicesGrid).EndInit();
        servicesToolbarPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)callsGrid).EndInit();
        callsToolbarPanel.ResumeLayout(false);
        processContextMenu.ResumeLayout(false);
        mainMenuStrip.ResumeLayout(false);
        mainMenuStrip.PerformLayout();
        tabHeaderPanel.ResumeLayout(false);
        ResumeLayout(false);
        PerformLayout();
    }

    private void AddDetailRow(int rowIndex, string labelText, out Label valueLabel)
    {
        var rowPanel = new Panel
        {
            BackColor = Color.FromArgb(30, 30, 30),
            Dock = DockStyle.Fill,
            Margin = new Padding(0, 0, 0, 8),
            Padding = new Padding(10, 6, 10, 6)
        };

        var titleLabel = new Label
        {
            Dock = DockStyle.Top,
            Font = new Font("Segoe UI", 8F, FontStyle.Bold),
            ForeColor = Color.FromArgb(156, 156, 160),
            Height = 16,
            Text = labelText.ToUpperInvariant(),
            Margin = new Padding(0),
            TextAlign = ContentAlignment.MiddleLeft
        };

        valueLabel = new Label
        {
            Dock = DockStyle.Fill,
            Font = rowIndex == 5 ? new Font("Consolas", 8.75F) : new Font("Segoe UI Semibold", 10F, FontStyle.Bold),
            ForeColor = Color.FromArgb(243, 243, 243),
            Margin = new Padding(0),
            Text = "-",
            AutoEllipsis = true,
            TextAlign = rowIndex == 5 ? ContentAlignment.TopLeft : ContentAlignment.MiddleLeft
        };

        rowPanel.Controls.Add(valueLabel);
        rowPanel.Controls.Add(titleLabel);
        detailsTableLayoutPanel.Controls.Add(rowPanel, 0, rowIndex);
    }
}

